// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TARetailOrder.ApiService.DataContext;

#nullable disable

namespace TARetailOrder.ApiService.DataContext.Migrations
{
    [DbContext(typeof(DBDataContext))]
    [Migration("20250629131510_Added-Category")]
    partial class AddedCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TARetailOrder.ApiService.DataContext.Models.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DeleterUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TARetailOrder.ApiService.DataContext.Models.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DeleterUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("715835a1-8fda-4a01-a33a-13d7e8c5a211"),
                            BillingAddress = "123 Main Street, Quezon City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 5, 30, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "john.smith@email.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Smith",
                            PhoneNo = "09123456789",
                            ShippingAddress = "123 Main Street, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("99106aaa-f41a-44a8-a5b9-a3512c52e02a"),
                            BillingAddress = "456 Rizal Avenue, Makati City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 4, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "maria.santos@gmail.com",
                            FirstName = "Maria",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 19, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            LastModifierUserId = 2,
                            LastName = "Santos",
                            PhoneNo = "09187654321",
                            ShippingAddress = "456 Rizal Avenue, Makati City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("e9501f79-c7c6-4965-91ea-b5c218938663"),
                            BillingAddress = "321 Ortigas Center, Pasig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 9, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "carlos.reyes@yahoo.com",
                            FirstName = "Carlos",
                            IsDeleted = false,
                            LastName = "Reyes",
                            PhoneNo = "09234567890",
                            ShippingAddress = "789 Commonwealth Ave, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("7077b7ad-9889-4fa4-86c4-bb9447248a14"),
                            BillingAddress = "147 Taft Avenue, Manila, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 14, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "ana.cruz@hotmail.com",
                            FirstName = "Ana",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 24, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            LastModifierUserId = 1,
                            LastName = "Cruz",
                            PhoneNo = "09198765432",
                            ShippingAddress = "147 Taft Avenue, Manila, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("4a3bdd7b-2402-451f-a762-0fc0d40bca59"),
                            BillingAddress = "258 EDSA, Mandaluyong City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 17, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "roberto.garcia@outlook.com",
                            FirstName = "Roberto",
                            IsDeleted = false,
                            LastName = "Garcia",
                            PhoneNo = "09345678901",
                            ShippingAddress = "258 EDSA, Mandaluyong City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("1ae376f1-f2ab-487f-b9fc-5847154a15c0"),
                            BillingAddress = "159 BGC, Taguig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 21, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "elena.mendoza@gmail.com",
                            FirstName = "Elena",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 27, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            LastModifierUserId = 2,
                            LastName = "Mendoza",
                            PhoneNo = "09456789012",
                            ShippingAddress = "369 Katipunan Avenue, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("4d2f0d4b-c11a-496b-b56a-5e973df1effa"),
                            BillingAddress = "741 Shaw Boulevard, Mandaluyong City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 23, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "miguel.torres@email.com",
                            FirstName = "Miguel",
                            IsDeleted = false,
                            LastName = "Torres",
                            PhoneNo = "09567890123",
                            ShippingAddress = "741 Shaw Boulevard, Mandaluyong City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("b59d783f-5d56-4c07-ba99-9c64dde2ae70"),
                            BillingAddress = "852 Alabang-Zapote Road, Las Piñas City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 25, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "isabella.flores@yahoo.com",
                            FirstName = "Isabella",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 28, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            LastModifierUserId = 1,
                            LastName = "Flores",
                            PhoneNo = "09678901234",
                            ShippingAddress = "852 Alabang-Zapote Road, Las Piñas City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("90c15a5e-ea52-40ff-8f34-fdd75c95b2f7"),
                            BillingAddress = "963 C5 Road, Pasig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 27, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1703),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            FirstName = "Diego",
                            IsDeleted = false,
                            LastName = "Villanueva",
                            PhoneNo = "09789012345",
                            ShippingAddress = "963 C5 Road, Pasig City, Metro Manila, Philippines"
                        });
                });

            modelBuilder.Entity("TARetailOrder.ApiService.DataContext.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DeleterUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("83b11927-44f7-430c-9729-d15e44160203"),
                            CreationTime = new DateTime(2025, 4, 30, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1953),
                            CreatorUserId = 0,
                            DeleterUserId = 0,
                            IsDeleted = false,
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("1116b811-4618-4728-b931-c5d5c257715a"),
                            CreationTime = new DateTime(2025, 5, 15, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1953),
                            CreatorUserId = 0,
                            DeleterUserId = 0,
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 19, 13, 15, 8, 364, DateTimeKind.Utc).AddTicks(1953),
                            LastModifierUserId = 1,
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==",
                            Role = 0,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
