// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TARetailOrder.ApiService.DataContext;

#nullable disable

namespace TARetailOrder.ApiService.DataContext.Migrations
{
    [DbContext(typeof(DBDataContext))]
    [Migration("20250629055628_Added-User")]
    partial class AddedUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TARetailOrder.ApiService.DataContext.Model.Customer", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DeleterUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            ID = new Guid("c2ccdcbb-6ad5-4794-a22b-4bbe98591047"),
                            BillingAddress = "123 Main Street, Quezon City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 5, 30, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "john.smith@email.com",
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Smith",
                            PhoneNo = "09123456789",
                            ShippingAddress = "123 Main Street, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("73d13cf0-ebf1-486a-9126-f6c8d7e55839"),
                            BillingAddress = "456 Rizal Avenue, Makati City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 4, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "maria.santos@gmail.com",
                            FirstName = "Maria",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 19, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            LastModifierUserId = 2,
                            LastName = "Santos",
                            PhoneNo = "09187654321",
                            ShippingAddress = "456 Rizal Avenue, Makati City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("9500043d-dc97-48f1-90f0-905c7879d766"),
                            BillingAddress = "321 Ortigas Center, Pasig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 9, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "carlos.reyes@yahoo.com",
                            FirstName = "Carlos",
                            IsDeleted = false,
                            LastName = "Reyes",
                            PhoneNo = "09234567890",
                            ShippingAddress = "789 Commonwealth Ave, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("7e60fcff-e7ce-4889-a5d1-52a3ae088a62"),
                            BillingAddress = "147 Taft Avenue, Manila, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 14, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "ana.cruz@hotmail.com",
                            FirstName = "Ana",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 24, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            LastModifierUserId = 1,
                            LastName = "Cruz",
                            PhoneNo = "09198765432",
                            ShippingAddress = "147 Taft Avenue, Manila, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("52fb4b74-2165-4d5f-a043-22bcdf77b23d"),
                            BillingAddress = "258 EDSA, Mandaluyong City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 17, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "roberto.garcia@outlook.com",
                            FirstName = "Roberto",
                            IsDeleted = false,
                            LastName = "Garcia",
                            PhoneNo = "09345678901",
                            ShippingAddress = "258 EDSA, Mandaluyong City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("f1ec74e9-7d96-48e6-99f9-324955a2076d"),
                            BillingAddress = "159 BGC, Taguig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 21, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "elena.mendoza@gmail.com",
                            FirstName = "Elena",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 27, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            LastModifierUserId = 2,
                            LastName = "Mendoza",
                            PhoneNo = "09456789012",
                            ShippingAddress = "369 Katipunan Avenue, Quezon City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("0eb5a0a5-0473-4996-b9c4-c6bc5babe911"),
                            BillingAddress = "741 Shaw Boulevard, Mandaluyong City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 23, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            Email = "miguel.torres@email.com",
                            FirstName = "Miguel",
                            IsDeleted = false,
                            LastName = "Torres",
                            PhoneNo = "09567890123",
                            ShippingAddress = "741 Shaw Boulevard, Mandaluyong City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("6e4646fd-2142-4f98-87a9-fde75feade5b"),
                            BillingAddress = "852 Alabang-Zapote Road, Las Piñas City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 25, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 1,
                            DeleterUserId = 0,
                            Email = "isabella.flores@yahoo.com",
                            FirstName = "Isabella",
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 28, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            LastModifierUserId = 1,
                            LastName = "Flores",
                            PhoneNo = "09678901234",
                            ShippingAddress = "852 Alabang-Zapote Road, Las Piñas City, Metro Manila, Philippines"
                        },
                        new
                        {
                            ID = new Guid("ad0f3f40-220d-475d-ad50-7b5d597c29a4"),
                            BillingAddress = "963 C5 Road, Pasig City, Metro Manila, Philippines",
                            CreationTime = new DateTime(2025, 6, 27, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3684),
                            CreatorUserId = 2,
                            DeleterUserId = 0,
                            FirstName = "Diego",
                            IsDeleted = false,
                            LastName = "Villanueva",
                            PhoneNo = "09789012345",
                            ShippingAddress = "963 C5 Road, Pasig City, Metro Manila, Philippines"
                        });
                });

            modelBuilder.Entity("TARetailOrder.ApiService.DataContext.Model.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("DeleterUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifierUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("4035045b-1d22-4909-94a6-6e3a327e9bf1"),
                            CreationTime = new DateTime(2025, 4, 30, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3937),
                            CreatorUserId = 0,
                            DeleterUserId = 0,
                            IsDeleted = false,
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==",
                            Role = 1,
                            Username = "admin"
                        },
                        new
                        {
                            ID = new Guid("26239625-fb11-45be-97e7-c4d087d8dd64"),
                            CreationTime = new DateTime(2025, 5, 15, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3937),
                            CreatorUserId = 0,
                            DeleterUserId = 0,
                            IsDeleted = false,
                            LastModificationTime = new DateTime(2025, 6, 19, 5, 56, 28, 1, DateTimeKind.Utc).AddTicks(3937),
                            LastModifierUserId = 1,
                            Password = "AM4OLBpptxBYmM79lGOX9egzZk3vIQU3d/gFCJzaBjAPXzYIK3tQ2N7X4fcrHtElTw==",
                            Role = 0,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
